'use client';
import { FormEvent, useState } from 'react';
import { createClient } from '@/lib/supabase/client';

export default function Login() {
  const [mode, setMode] = useState<'login'|'signup'>('login');
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [name, setName] = useState(''); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); setMessage(''); const s = createClient(); const r = mode === 'login' ? await s.auth.signInWithPassword({ email, password }) : await s.auth.signUp({ email, password, options: { data: { name } } }); setBusy(false); if (r.error) return setMessage(r.error.message); window.location.href = '/dashboard'; }
  return <main dir="rtl" className="grid min-h-screen bg-background lg:grid-cols-2">
    <section className="hidden overflow-hidden bg-primary p-10 text-primary-foreground lg:flex lg:flex-col lg:justify-between"><div><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-2xl bg-white text-lg font-black text-black">ر</span><b className="text-2xl">رابطك.</b></div><div className="mt-24 max-w-lg"><p className="text-sm font-bold opacity-50">YOUR DIGITAL HOME</p><h1 className="mt-5 text-6xl font-black leading-[1.05]">لا تحتاج أكثر من رابط واحد.</h1><p className="mt-6 text-lg leading-8 opacity-60">صفحة شخصية، متجر صغير، خدمات، واتساب وتحليلات — كلها تحت اسمك.</p></div></div><div className="flex items-center justify-between text-xs opacity-40"><span>© رابطك</span><span>بسيط. سريع. مختلف.</span></div></section>
    <section className="flex items-center justify-center p-5 sm:p-10"><form onSubmit={submit} className="w-full max-w-md"><div className="mb-10 lg:hidden"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-2xl bg-primary font-black text-primary-foreground">ر</span><b className="text-xl">رابطك.</b></div></div><p className="text-sm font-bold text-neutral-400">{mode === 'login' ? 'مرحباً بعودتك' : 'ابدأ حضورك الرقمي'}</p><h2 className="mt-2 text-4xl font-black tracking-tight">{mode === 'login' ? 'سجّل دخولك.' : 'أنشئ حسابك.'}</h2><p className="mt-3 text-sm text-muted">{mode === 'login' ? 'أكمل من حيث توقفت.' : 'أول صفحة لك تبدأ من هنا.'}</p>{mode === 'signup' && <input required value={name} onChange={e=>setName(e.target.value)} placeholder="الاسم" className="mt-8 w-full rounded-2xl border bg-card p-4 outline-none transition focus:ring-2 focus:ring-black/10"/>}<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="البريد الإلكتروني" className="mt-4 w-full rounded-2xl border bg-card p-4 outline-none transition focus:ring-2 focus:ring-black/10"/><input required minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="كلمة المرور (8 أحرف على الأقل)" className="mt-4 w-full rounded-2xl border bg-card p-4 outline-none transition focus:ring-2 focus:ring-black/10"/><button disabled={busy} className="mt-5 w-full rounded-2xl bg-primary p-4 font-black text-primary-foreground transition hover:-translate-y-0.5 disabled:opacity-50">{busy ? 'جارٍ المعالجة…' : mode === 'login' ? 'دخول إلى رابطك →' : 'إنشاء الحساب →'}</button>{message && <p className="mt-3 rounded-xl bg-red-50 p-3 text-sm text-red-600">{message}</p>}<button type="button" onClick={()=>setMode(mode==='login'?'signup':'login')} className="mt-6 w-full text-sm font-bold text-muted hover:text-foreground">{mode==='login' ? 'ليس لديك حساب؟ أنشئ واحداً' : 'لديك حساب؟ سجّل الدخول'}</button></form></section>
  </main>;
}
