import Link from 'next/link';
import { redirect } from 'next/navigation';
import { currentUser, myPage, myProducts, myServices } from '@/lib/data';

export default async function Dashboard() {
  const u = await currentUser();
  if (!u) redirect('/login');
  const [p, products, services] = await Promise.all([myPage(), myProducts(), myServices()]);
  return <div className="space-y-8">
    <section className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-sm font-bold text-neutral-400">الأربعاء، أهلاً بك 👋</p><h1 className="mt-1 text-4xl font-black tracking-tight">مرحباً {p?.name || u.email}</h1><p className="mt-2 text-sm text-muted">هذه نظرة سريعة على مساحة رابطك اليوم.</p></div>{p && <Link href={`/${p.username}`} target="_blank" className="rounded-2xl border bg-card px-5 py-3 text-sm font-black shadow-sm transition hover:-translate-y-0.5">فتح صفحتي ↗</Link>}</section>
    <section className="overflow-hidden rounded-[2rem] bg-primary p-7 text-primary-foreground shadow-2xl shadow-black/10 sm:p-9"><div className="flex flex-wrap items-center justify-between gap-8"><div><span className="rounded-full bg-white/10 px-3 py-1 text-xs font-bold">رابطك اليوم</span><h2 className="mt-5 max-w-xl text-3xl font-black leading-tight sm:text-4xl">خلّي صفحتك تعكسك.<br/>وخلّي الرابط يعمل بدالك.</h2><p className="mt-4 max-w-lg text-sm leading-7 opacity-60">أضف محتواك، رتّب أقسامك، ثم شارك الرابط مع جمهورك.</p></div><Link href="/dashboard/builder" className="rounded-2xl bg-accent px-6 py-4 text-sm font-black text-accent-foreground">تعديل الصفحة →</Link></div></section>
    <section className="grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border bg-card p-5"><p className="text-xs font-bold text-muted">حالة الصفحة</p><div className="mt-3 flex items-center gap-2"><span className="size-2.5 rounded-full bg-lime-400"/><b className="text-xl">{p?.published ? 'منشورة' : 'مسودة'}</b></div></div><div className="rounded-2xl border bg-card p-5"><p className="text-xs font-bold text-muted">المنتجات</p><b className="mt-3 block text-3xl">{products.length}</b></div><div className="rounded-2xl border bg-card p-5"><p className="text-xs font-bold text-muted">الخدمات</p><b className="mt-3 block text-3xl">{services.length}</b></div></section>
    <section><div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-black">اختصارات سريعة</h2><span className="text-xs text-muted">أدواتك الأساسية</span></div><div className="grid gap-4 md:grid-cols-2"><Link href="/dashboard/builder" className="group rounded-2xl border bg-card p-6 transition hover:-translate-y-1 hover:shadow-lg"><span className="grid size-10 place-items-center rounded-xl bg-accent font-black">✦</span><h3 className="mt-5 text-lg font-black">باني الصفحة</h3><p className="mt-1 text-sm text-muted">غيّر الأقسام، الروابط والمظهر.</p><span className="mt-5 block text-sm font-black">فتح الباني →</span></Link><Link href="/dashboard/analytics" className="group rounded-2xl border bg-card p-6 transition hover:-translate-y-1 hover:shadow-lg"><span className="grid size-10 place-items-center rounded-xl bg-soft font-black">↗</span><h3 className="mt-5 text-lg font-black">التحليلات</h3><p className="mt-1 text-sm text-muted">افهم المشاهدات والتفاعل.</p><span className="mt-5 block text-sm font-black">عرض التحليلات →</span></Link></div></section>
  </div>;
}
